import type { Fable } from "./types.js";

export const SEED_FABLES: Fable[] = [
  {
    id: "f001",
    title: "The Tortoise and the Hare",
    author: "Aesop",
    text: "A hare once mocked a tortoise for being slow. \"Want to race?\" asked the tortoise. The hare laughed and agreed. The hare ran fast and soon was far ahead. Seeing the tortoise still plodding along, the hare decided to nap. When the hare woke, the tortoise was crossing the finish line. Slow and steady wins the race.",
    length: "short",
    ageSuitability: "4+",
    tags: ["bravery", "wisdom"],
    language: "en",
    createdAt: "2025-01-01T00:00:00Z",
    flagged: false,
  },
  {
    id: "f002",
    title: "The Boy Who Cried Wolf",
    author: "Aesop",
    text: "A shepherd boy grew bored watching his sheep. He shouted \"Wolf! Wolf!\" The villagers rushed to help, but there was no wolf. He did this again, and again the villagers came. One day a wolf really appeared. The boy cried out, but the villagers thought it was another trick and stayed home. The wolf carried off a sheep. Never lie, even in jest.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty"],
    language: "en",
    createdAt: "2025-01-02T00:00:00Z",
    flagged: false,
  },
  {
    id: "f003",
    title: "The Lion and the Mouse",
    author: "Aesop",
    text: "A lion caught a tiny mouse. The mouse begged to be let go, promising to help someday. The lion laughed but let the mouse go. Later, hunters trapped the lion in a net. The mouse chewed the ropes and set the lion free. Even the smallest friend can be the greatest help.",
    length: "short",
    ageSuitability: "4+",
    tags: ["friendship", "kindness"],
    language: "en",
    createdAt: "2025-01-03T00:00:00Z",
    flagged: false,
  },
  {
    id: "f004",
    title: "The Fox and the Grapes",
    author: "Aesop",
    text: "A fox saw ripe grapes hanging high on a vine. He jumped and jumped but could not reach them. Tired and frustrated, the fox walked away, saying \"I am sure they are sour anyway.\" It is easy to despise what you cannot get.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-01-04T00:00:00Z",
    flagged: false,
  },
  {
    id: "f005",
    title: "The Ant and the Grasshopper",
    author: "Aesop",
    text: "All summer the ant worked hard storing food. The grasshopper sang and played. When winter came, the ant was warm and fed. The grasshopper was cold and hungry. \"Sing now?\" said the ant. \"You sang all summer; now dance in the snow.\" Work today, enjoy tomorrow.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-01-05T00:00:00Z",
    flagged: false,
  },
  {
    id: "f006",
    title: "The Ugly Duckling",
    author: "Hans Christian Andersen",
    text: "A duckling was different from his siblings. He was bigger, greyer, and clumsier. The other ducks pecked at him. He wandered alone through the winter. In spring, he saw a group of beautiful swans. He swam toward them, expecting to be chased away. Instead, they welcomed him. He had been a swan all along.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["bravery", "friendship"],
    language: "en",
    createdAt: "2025-01-06T00:00:00Z",
    flagged: false,
  },
  {
    id: "f007",
    title: "The Goose That Laid Golden Eggs",
    author: "Aesop",
    text: "A man owned a goose that laid a golden egg every day. He grew greedy and thought the goose must be filled with gold inside. He killed the goose and cut it open, finding nothing special. Greed often overreaches itself.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-01-07T00:00:00Z",
    flagged: false,
  },
  {
    id: "f008",
    title: "The Three Little Pigs",
    author: "Joseph Jacobs",
    text: "Three pigs left home to seek their fortune. The first built a house of straw, the second of sticks, and the third of bricks. A wolf came and blew down the straw and stick houses. The pigs ran to the brick house. The wolf could not blow it down. Hard work and patience keep you safe.",
    length: "medium",
    ageSuitability: "4+",
    tags: ["bravery", "wisdom"],
    language: "en",
    createdAt: "2025-01-08T00:00:00Z",
    flagged: false,
  },
  {
    id: "f009",
    title: "The Magic Porridge Pot",
    author: "Brothers Grimm",
    text: "A kind girl received a magic pot that cooked porridge when told \"Cook, pot!\" and stopped when told \"Stop, pot!\" She went away and told her mother, who forgot the stop words. Porridge filled the whole village. The girl returned and said \"Stop, pot!\" and the porridge stopped. Kindness and memory both matter.",
    length: "medium",
    ageSuitability: "4+",
    tags: ["magic", "kindness"],
    language: "en",
    createdAt: "2025-01-09T00:00:00Z",
    flagged: false,
  },
  {
    id: "f010",
    title: "The Fox and the Crow",
    author: "Aesop",
    text: "A crow found a piece of cheese and flew to a branch to eat it. A fox saw her and wanted the cheese. \"What beautiful feathers!\" said the fox. \"I am sure your voice is beautiful too.\" The crow was pleased and opened her beak to sing. The cheese fell to the ground. The fox grabbed it and ran. Flattery rarely brings true rewards.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-01-10T00:00:00Z",
    flagged: false,
  },
  {
    id: "f011",
    title: "The Pied Piper of Hamelin",
    author: "Brothers Grimm",
    text: "The town of Hamelin was overrun with rats. A piper in colorful clothes promised to remove them for a fee. He played his pipe and the rats followed him to the river, where they drowned. When the townspeople refused to pay, the piper played again, and this time the children followed him and were never seen again. Keep your promises.",
    length: "long",
    ageSuitability: "7+",
    tags: ["adventure", "honesty"],
    language: "en",
    createdAt: "2025-01-11T00:00:00Z",
    flagged: false,
  },
  {
    id: "f012",
    title: "The Golden Touch",
    author: "Nathaniel Hawthorne",
    text: "King Midas wished that everything he touched would turn to gold. His wish was granted. His food turned to gold. His drink turned to gold. Even his beloved daughter turned to gold when he embraced her. Midas begged to have the gift taken away. He learned that gold is not the most precious thing in the world.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["magic", "wisdom"],
    language: "en",
    createdAt: "2025-01-12T00:00:00Z",
    flagged: false,
  },
  {
    id: "f013",
    title: "The Empty Pot",
    author: "Demi",
    text: "A Chinese emperor searched for a successor. He gave every child a seed and said the one who grew the most beautiful plant would become the next emperor. A boy named Ping carefully tended his seed, but nothing grew. He brought the empty pot to the emperor. The emperor smiled and said, \"The seeds were boiled. You are the only one honest enough to bring an empty pot.\" Honesty is the greatest virtue.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["honesty", "nature"],
    language: "en",
    createdAt: "2025-01-13T00:00:00Z",
    flagged: false,
  },
  {
    id: "f014",
    title: "The Enormous Turnip",
    author: "Aesop",
    text: "A farmer planted a turnip seed. It grew into an enormous turnip. He tried to pull it out but could not. He called his wife, who called their daughter, who called the dog, who called the cat, who called the mouse. Together they pulled and pulled until pop! The turnip came out. Many hands make light work.",
    length: "short",
    ageSuitability: "3+",
    tags: ["friendship", "kindness"],
    language: "en",
    createdAt: "2025-01-14T00:00:00Z",
    flagged: false,
  },
  {
    id: "f015",
    title: "Jack and the Beanstalk",
    author: "Joseph Jacobs",
    text: "Jack traded his cow for magic beans. His mother was angry and threw them out the window. Overnight, a enormous beanstalk grew. Jack climbed it and found a castle with a giant. He took a golden harp and a hen that laid golden eggs. The giant chased him, but Jack cut down the beanstalk. Sometimes a small boy can do great things.",
    length: "long",
    ageSuitability: "5+",
    tags: ["adventure", "magic"],
    language: "en",
    createdAt: "2025-01-15T00:00:00Z",
    flagged: false,
  },
  {
    id: "f016",
    title: "The Owl and the Pussycat",
    author: "Edward Lear",
    text: "The owl and the pussycat went to sea in a beautiful pea-green boat. They took honey and plenty of money. The owl looked at the moon and sang to the pussycat. They married by the turkey who lived on the hill. They lived happily ever after in a tree by the sea. Love sees no differences.",
    length: "short",
    ageSuitability: "3+",
    tags: ["friendship", "magic"],
    language: "en",
    createdAt: "2025-01-16T00:00:00Z",
    flagged: false,
  },
  {
    id: "f017",
    title: "Little Red Riding Hood",
    author: "Brothers Grimm",
    text: "A girl in a red hood was sent to bring food to her grandmother. A wolf tricked her into taking a different path. He raced to grandmother's house and ate her up. When Little Red Riding Hood arrived, the wolf dressed as grandmother and tricked her too. A woodcutter came and rescued them both. Always be careful of strangers.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["bravery", "adventure"],
    language: "en",
    createdAt: "2025-01-17T00:00:00Z",
    flagged: false,
  },
  {
    id: "f018",
    title: "The Elves and the Shoemaker",
    author: "Brothers Grimm",
    text: "A poor shoemaker and his wife found beautiful shoes made on their workbench overnight. Two tiny elves had made them. The shoemaker and his wife made little clothes for the elves. The elves were delighted and never returned. Kindness is always rewarded.",
    length: "medium",
    ageSuitability: "4+",
    tags: ["kindness", "friendship"],
    language: "en",
    createdAt: "2025-01-18T00:00:00Z",
    flagged: false,
  },
  {
    id: "f019",
    title: "The Fisherman and His Wife",
    author: "Brothers Grimm",
    text: "A fisherman caught an enchanted flounder. The flounder begged to be released, and the fisherman let it go. His wife asked him to wish for a cottage, then a castle, then to be king, then to be pope. At last she wished to command the sun and moon. The flounder put them back in their old shack. Greed has no end.",
    length: "long",
    ageSuitability: "6+",
    tags: ["nature", "honesty"],
    language: "en",
    createdAt: "2025-01-19T00:00:00Z",
    flagged: false,
  },
  {
    id: "f020",
    title: "The Snow Queen",
    author: "Hans Christian Andersen",
    text: "A mirror broke into pieces and one shard entered a boy's eye, making him see only ugliness. The Snow Queen took him to her palace. His friend Gerda searched for him through forests and castles. Her warm tears melted the ice in his heart. He remembered who he was. Love conquers all.",
    length: "long",
    ageSuitability: "7+",
    tags: ["magic", "friendship", "bravery"],
    language: "en",
    createdAt: "2025-01-20T00:00:00Z",
    flagged: false,
  },
  {
    id: "f021",
    title: "The Lion and the Fox",
    author: "Aesop",
    text: "A fox entered a lion's den and saw a cave full of bones. The lion had lured many animals in with his friendly voice. The fox learned to watch where others had gone wrong. Learn from others' mistakes.",
    length: "short",
    ageSuitability: "6+",
    tags: ["wisdom", "adventure"],
    language: "en",
    createdAt: "2025-01-21T00:00:00Z",
    flagged: false,
  },
  {
    id: "f022",
    title: "The Farmer and the Stork",
    author: "Aesop",
    text: "A farmer set nets to catch cranes. A stork was caught among them. \"Please let me go,\" said the stork. \"I am not a crane; I am a stork, known for kindness.\" The farmer replied, \"You flew with cranes; you will be treated like a crane.\" You are judged by the company you keep.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-01-22T00:00:00Z",
    flagged: false,
  },
  {
    id: "f023",
    title: "The Monkey and the Dolphin",
    author: "Aesop",
    text: "A monkey was sailing with a dolphin when the ship sank. The monkey could not swim. \"Save me!\" he cried. The dolphin asked if he lived in Athens. The monkey said yes. The dolphin asked if he knew Piraeus. The monkey lied and said yes. The dolphin dove and left the monkey to drown. Never lie, even to impress.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "nature"],
    language: "en",
    createdAt: "2025-01-23T00:00:00Z",
    flagged: false,
  },
  {
    id: "f024",
    title: "The Wizard of Oz",
    author: "L. Frank Baum",
    text: "Dorothy was swept from Kansas to the Land of Oz. She followed the yellow brick road to find the Wizard, who promised to send her home. Along the way she met the Scarecrow who wanted a brain, the Tin Man who wanted a heart, and the Lion who wanted courage. The Wizard gave them gifts, but they had already proven they had what they sought. There is no place like home.",
    length: "long",
    ageSuitability: "6+",
    tags: ["adventure", "friendship", "bravery"],
    language: "en",
    createdAt: "2025-01-24T00:00:00Z",
    flagged: false,
  },
  {
    id: "f025",
    title: "The Brave Little Tailor",
    author: "Brothers Grimm",
    text: "A tailor killed seven flies at once and embroidered \"Seven at One Blow\" on his belt. People thought he was a hero. He went on adventures and defeated giants with cleverness, not strength. He became a king. Wit is stronger than might.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["bravery", "adventure"],
    language: "en",
    createdAt: "2025-01-25T00:00:00Z",
    flagged: false,
  },
  {
    id: "f026",
    title: "The Giving Tree",
    author: "Shel Silverstein",
    text: "A tree loved a boy. She gave him apples, her branches, and finally her trunk. The boy grew old and wanted only a quiet place to sit. The stump remained. The tree was happy. Giving brings true joy.",
    length: "medium",
    ageSuitability: "4+",
    tags: ["kindness", "nature"],
    language: "en",
    createdAt: "2025-01-26T00:00:00Z",
    flagged: false,
  },
  {
    id: "f027",
    title: "The Red Shoes",
    author: "Hans Christian Andersen",
    text: "Karen received a pair of red shoes and wore them to church. The shoes would not stop dancing. They danced through fields and thorns. A soldier helped her take them off. Karen never wore red shoes again. Vanity can lead to suffering.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["magic", "wisdom"],
    language: "en",
    createdAt: "2025-01-27T00:00:00Z",
    flagged: false,
  },
  {
    id: "f028",
    title: "The Emperor's New Clothes",
    author: "Hans Christian Andersen",
    text: "A vain emperor was tricked by swindlers who promised invisible cloth. No one dared say they could not see it, until a child shouted, \"He has nothing on!\" The emperor walked on. Truth needs courage.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["honesty", "bravery"],
    language: "en",
    createdAt: "2025-01-28T00:00:00Z",
    flagged: false,
  },
  {
    id: "f029",
    title: "The Little Mermaid",
    author: "Hans Christian Andersen",
    text: "A mermaid traded her voice for legs to be with a prince. She danced for him, though it hurt. The prince married another. At dawn the mermaid would turn to foam. Her sisters gave her a knife: kill the prince and live. She chose to throw the knife into the sea and turned to foam. Selfless love endures.",
    length: "long",
    ageSuitability: "7+",
    tags: ["magic", "kindness", "bravery"],
    language: "en",
    createdAt: "2025-01-29T00:00:00Z",
    flagged: false,
  },
  {
    id: "f030",
    title: "The Wind and the Sun",
    author: "Aesop",
    text: "The wind and the sun argued about who was stronger. They saw a traveler and made a bet: whoever could make him remove his coat would win. The wind blew hard, but the traveler pulled his coat tighter. The sun shone warmly, and the traveler removed his coat. Gentleness is stronger than force.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-01-30T00:00:00Z",
    flagged: false,
  },
  {
    id: "f031",
    title: "The Frog Prince",
    author: "Brothers Grimm",
    text: "A princess dropped her golden ball into a well. A frog retrieved it and asked to live with her. She agreed reluctantly. The frog turned into a prince when she kissed him. Do not judge by appearances.",
    length: "medium",
    ageSuitability: "4+",
    tags: ["magic", "kindness"],
    language: "en",
    createdAt: "2025-01-31T00:00:00Z",
    flagged: false,
  },
  {
    id: "f032",
    title: "The Farmer and the Viper",
    author: "Aesop",
    text: "A farmer found a frozen viper and warmed it by his fire. The viper revived and bit him. \"You knew what I was when you picked me up,\" said the viper. Do not help the unworthy.",
    length: "short",
    ageSuitability: "6+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-01T00:00:00Z",
    flagged: false,
  },
  {
    id: "f033",
    title: "The Thirsty Crow",
    author: "Aesop",
    text: "A crow was thirsty and found a pitcher with a little water at the bottom. She could not reach it. She dropped pebbles into the pitcher one by one. The water rose to the top. Cleverness solves problems.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-02-02T00:00:00Z",
    flagged: false,
  },
  {
    id: "f034",
    title: "Puss in Boots",
    author: "Charles Perrault",
    text: "A miller left his son a cat instead of a fortune. The cat promised to help. He dressed in boots, caught rabbits and birds, and introduced his master to the king as the Marquis of Carabas. The king was impressed and gave the young man a castle and his daughter's hand. A clever cat can change your life.",
    length: "long",
    ageSuitability: "5+",
    tags: ["magic", "adventure", "friendship"],
    language: "en",
    createdAt: "2025-02-03T00:00:00Z",
    flagged: false,
  },
  {
    id: "f035",
    title: "Cinderella",
    author: "Charles Perrault",
    text: "A kind girl was mistreated by her stepmother and stepsisters. She was forbidden to go to the ball. Her fairy godmother turned a pumpkin into a coach and gave her glass slippers. She danced with the prince and fled at midnight, leaving a slipper. The prince searched for her with the slipper. It fit only Cinderella. Kindness is rewarded.",
    length: "long",
    ageSuitability: "5+",
    tags: ["magic", "kindness", "bravery"],
    language: "en",
    createdAt: "2025-02-04T00:00:00Z",
    flagged: false,
  },
  {
    id: "f036",
    title: "The Happy Prince",
    author: "Oscar Wilde",
    text: "A golden statue of a prince stood in the city. A swallow helped him give his gold to the poor. They took his gems and gold until he was plain. The swallow died of cold. The prince and the swallow were melted down, but God chose them as the most precious in the city. True beauty is in giving.",
    length: "long",
    ageSuitability: "6+",
    tags: ["kindness", "friendship"],
    language: "en",
    createdAt: "2025-02-05T00:00:00Z",
    flagged: false,
  },
  {
    id: "f037",
    title: "The Nightingale",
    author: "Hans Christian Andersen",
    text: "The nightingale sang beautifully for the emperor. A mechanical bird replaced her. The nightingale returned to sing for the sick emperor, bringing him health. The mechanical bird broke. The real bird was better than any machine. Nothing artificial can replace nature.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["nature", "magic"],
    language: "en",
    createdAt: "2025-02-06T00:00:00Z",
    flagged: false,
  },
  {
    id: "f038",
    title: "The Selfish Giant",
    author: "Oscar Wilde",
    text: "A giant built a wall to keep children out of his garden. Spring never came. One day children snuck in, and spring returned. The giant tore down the wall and opened his garden. The giant learned to share. Sharing brings happiness.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["kindness", "nature"],
    language: "en",
    createdAt: "2025-02-07T00:00:00Z",
    flagged: false,
  },
  {
    id: "f039",
    title: "The Star-Child",
    author: "Oscar Wilde",
    text: "A child fell from the stars and was raised by a woodcutter. He grew beautiful but cruel. He treated a beggar cruelly and was turned hideous. He searched for his mother and was kind to a leper who was his mother in disguise. He became beautiful again and became a king. Beauty comes from within.",
    length: "long",
    ageSuitability: "7+",
    tags: ["magic", "kindness", "adventure"],
    language: "en",
    createdAt: "2025-02-08T00:00:00Z",
    flagged: false,
  },
  {
    id: "f040",
    title: "The Fisherman and the Goldfish",
    author: "Alexander Pushkin",
    text: "A fisherman caught a golden fish that begged to be freed. He let it go. His wife demanded more and more gifts. The fish granted them all. At last she wanted to rule the sea. The fish said nothing and left them in their old hut. Greed returns you to where you began.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["magic", "honesty"],
    language: "en",
    createdAt: "2025-02-09T00:00:00Z",
    flagged: false,
  },
  {
    id: "f041",
    title: "The Remarkable Rocket",
    author: "Oscar Wilde",
    text: "A rocket thought he was the center of attention at a prince's wedding. He talked about himself endlessly. No one listened. He ended up in the gutter. Self-importance is not the same as importance.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-02-10T00:00:00Z",
    flagged: false,
  },
  {
    id: "f042",
    title: "The Nightingale and the Rose",
    author: "Oscar Wilde",
    text: "A nightingale sacrificed her life to create a red rose for a student who needed one to impress a girl. The student took the rose, but the girl rejected it. He threw it away. The rose was wasted on someone who did not appreciate it. True sacrifice is rare and often unrecognized.",
    length: "long",
    ageSuitability: "7+",
    tags: ["kindness", "nature"],
    language: "en",
    createdAt: "2025-02-11T00:00:00Z",
    flagged: false,
  },
  {
    id: "f043",
    title: "The Devoted Friend",
    author: "Oscar Wilde",
    text: "Hans was kind to everyone. His friend the miller only took from him. The miller sent Hans to get flour in the snow and took his wheelbarrow. Hans got lost and was found dead. The miller said, \"Loyalty is a terrible thing.\" True friendship goes both ways.",
    length: "long",
    ageSuitability: "7+",
    tags: ["friendship", "honesty"],
    language: "en",
    createdAt: "2025-02-12T00:00:00Z",
    flagged: false,
  },
  {
    id: "f044",
    title: "The Birthday of the Infanta",
    author: "Oscar Wilde",
    text: "An ugly dwarf danced for the Infanta at her birthday party. She laughed at him. He saw his reflection and died of a broken heart. Beauty can be cruel without kindness.",
    length: "medium",
    ageSuitability: "7+",
    tags: ["kindness", "wisdom"],
    language: "en",
    createdAt: "2025-02-13T00:00:00Z",
    flagged: false,
  },
  {
    id: "f045",
    title: "The Fish and the Ring",
    author: "Joseph Jacobs",
    text: "A magician turned a fish into a beautiful maiden. The fisherman married her. The magician wanted her back. The fisherman and his wife escaped through many magical transformations. Together they overcame every challenge. Love and teamwork conquer all.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["magic", "friendship", "adventure"],
    language: "en",
    createdAt: "2025-02-14T00:00:00Z",
    flagged: false,
  },
  {
    id: "f046",
    title: "The Clever peasant's daughter",
    author: "Brothers Grimm",
    text: "A peasant's daughter was sent to the king with a flower that blooms at night. The king said she could be queen if she came without a horse and not on foot. She rode a goat. The king was impressed. She answered his riddles wisely and became queen. Wisdom is the greatest wealth.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["wisdom", "adventure"],
    language: "en",
    createdAt: "2025-02-15T00:00:00Z",
    flagged: false,
  },
  {
    id: "f047",
    title: "The Blue Bird",
    author: "Maurice Maeterlinck",
    text: "Two children searched the world for the blue bird of happiness. They found it in their own home. They shared it with a sick neighbor's child, who was healed. The blue bird flew away but came back. Happiness is at home and grows when shared.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["magic", "kindness", "adventure"],
    language: "en",
    createdAt: "2025-02-16T00:00:00Z",
    flagged: false,
  },
  {
    id: "f048",
    title: "The Nutcracker and the Mouse King",
    author: "E. T. A. Hoffmann",
    text: "Clara received a nutcracker from her godfather. At midnight the nutcracker came to life and fought the Mouse King. Clara helped by throwing her slipper. The nutcracker turned into a prince and took her to the Land of Sweets. Courage and imagination open magical doors.",
    length: "long",
    ageSuitability: "6+",
    tags: ["magic", "bravery", "adventure"],
    language: "en",
    createdAt: "2025-02-17T00:00:00Z",
    flagged: false,
  },
  {
    id: "f049",
    title: "The Velveteen Rabbit",
    author: "Margery Williams",
    text: "A stuffed rabbit wanted to become real. A fairy told him that real happens when a child loves you for a long time. The rabbit became worn and shabby. The fairy returned and turned him into a real rabbit. Being loved makes you real.",
    length: "medium",
    ageSuitability: "5+",
    tags: ["kindness", "magic"],
    language: "en",
    createdAt: "2025-02-18T00:00:00Z",
    flagged: false,
  },
  {
    id: "f050",
    title: "The Wise Old Owl",
    author: "Mary Frances Knowles",
    text: "An owl lived in a tree. She spoke only once a day and wisely. The other birds came to hear her. She listened before she spoke. She thought before she answered. Listening and thinking bring wisdom.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-02-19T00:00:00Z",
    flagged: false,
  },
  {
    id: "f051",
    title: "The Hare and the Tortoise (Rematch)",
    author: "Aesop",
    text: "The hare challenged the tortoise to a rematch. This time the hare ran steadily and did not stop. The tortoise walked slowly but consistently. The hare reached the finish first. The tortoise said, \"Well run!\" The hare said, \"Well walked!\" Respect your opponent, even in victory.",
    length: "short",
    ageSuitability: "5+",
    tags: ["bravery", "friendship"],
    language: "en",
    createdAt: "2025-02-20T00:00:00Z",
    flagged: false,
  },
  {
    id: "f052",
    title: "The Crow and the Pitcher",
    author: "Aesop",
    text: "A thirsty crow found a pitcher with water she could not reach. She dropped pebbles in until the water rose. Patience and cleverness solve hard problems.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-02-21T00:00:00Z",
    flagged: false,
  },
  {
    id: "f053",
    title: "The Boy and the Filberts",
    author: "Aesop",
    text: "A boy put his hand into a jar of filberts and grabbed a big handful. He tried to pull his hand out but the neck of the jar was too narrow. He began to cry. His mother said, \"Take only half as many, and your hand will come out easily.\" Greed makes you lose everything.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-22T00:00:00Z",
    flagged: false,
  },
  {
    id: "f054",
    title: "The North Wind and the Sun",
    author: "Aesop",
    text: "The North Wind and the Sun argued about who was stronger. They watched a traveler and made a bet: whoever could make him remove his coat would win. The Wind blew hard, but the traveler pulled his coat tighter. The Sun shone warmly, and the traveler removed his coat. Kindness is more effective than force.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-02-23T00:00:00Z",
    flagged: false,
  },
  {
    id: "f055",
    title: "The Dog and the Shadow",
    author: "Aesop",
    text: "A dog found a piece of meat and carried it home over a bridge. He saw his reflection in the water and thought it was another dog with a bigger piece. He snapped at the reflection and dropped his own meat. Greed makes you lose what you have.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-24T00:00:00Z",
    flagged: false,
  },
  {
    id: "f056",
    title: "The Milkmaid and Her Pail",
    author: "Aesop",
    text: "A milkmaid carried a pail of milk on her head and dreamed of all she would buy. She tossed her head and spilled the milk. Do not count your chickens before they hatch.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-25T00:00:00Z",
    flagged: false,
  },
  {
    id: "f057",
    title: "The Wolf in Sheep's Clothing",
    author: "Aesop",
    text: "A wolf put on a sheepskin and joined the flock. He planned to eat a sheep each night. The shepherd, wanting a sheep for supper, chose the wolf by mistake. Disguise does not change your nature.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-02-26T00:00:00Z",
    flagged: false,
  },
  {
    id: "f058",
    title: "The Heifer and the Ox",
    author: "Aesop",
    text: "A heifer saw an ox yoked to a plow and pitied him. But the ox said, \"Look at the farmer's hand — he is stronger than both of us. We must obey.\" Be grateful for your freedom.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-27T00:00:00Z",
    flagged: false,
  },
  {
    id: "f059",
    title: "The Miser and His Gold",
    author: "Aesop",
    text: "A miser buried his gold. He visited it every day. A worker saw him and learned the secret. He dug up the gold and spent it. The miser wept. A neighbor said, \"Bury a stone in its place and imagine it is your gold. It will be just as useful.\" Possession without use is worthless.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-02-28T00:00:00Z",
    flagged: false,
  },
  {
    id: "f060",
    title: "The Bundle of Sticks",
    author: "Aesop",
    text: "A father gave his sons a bundle of sticks and asked them to break it. None could. He untied the bundle and each stick broke easily. United, you are strong. Divided, you are weak.",
    length: "short",
    ageSuitability: "4+",
    tags: ["friendship", "wisdom"],
    language: "en",
    createdAt: "2025-03-01T00:00:00Z",
    flagged: false,
  },
  {
    id: "f061",
    title: "The Fox and the Goat",
    author: "Aesop",
    text: "A fox fell into a well. A goat asked if the water was good. The fox said it was the finest he ever tasted. The goat jumped in. The fox climbed out using the goat's horns. Think before you act.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-02T00:00:00Z",
    flagged: false,
  },
  {
    id: "f062",
    title: "The Ass and His Purchaser",
    author: "Aesop",
    text: "A man wanted to buy a donkey. He asked to try one. The donkey worked hard all day but ate little. The seller was disappointed and said, \"Do not take him — he will surely eat us out of house and home.\" Appearances deceive.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-03T00:00:00Z",
    flagged: false,
  },
  {
    id: "f063",
    title: "The Eagle and the Arrow",
    author: "Aesop",
    text: "An eagle was shot by an arrow feathered with its own plumes. Dying, it said, \"We give our enemies the means of our own destruction.\" We often help those who harm us.",
    length: "short",
    ageSuitability: "6+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-03-04T00:00:00Z",
    flagged: false,
  },
  {
    id: "f064",
    title: "The Wild Boar and the Fox",
    author: "Aesop",
    text: "A wild boar sharpened his tusks on a tree. A fox asked why, since no one was hunting him. The boar said, \"When the hunt begins, I will not have time.\" Prepare before you need to.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-03-05T00:00:00Z",
    flagged: false,
  },
  {
    id: "f065",
    title: "The Hart and the Hunter",
    author: "Aesop",
    text: "A hart admired his own antlers but hated his thin legs. When a hunter chased him, his legs carried him swiftly, but his antlers caught in a bush. The hunter caught him. What we reject often saves us; what we admire may destroy us.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-03-06T00:00:00Z",
    flagged: false,
  },
  {
    id: "f066",
    title: "The Trees and the Axe",
    author: "Aesop",
    text: "A man asked the trees for a handle for his axe. The trees gave him an ash branch. With it, he cut them all down. Be careful what you give to those who would harm you.",
    length: "short",
    ageSuitability: "5+",
    tags: ["nature", "wisdom"],
    language: "en",
    createdAt: "2025-03-07T00:00:00Z",
    flagged: false,
  },
  {
    id: "f067",
    title: "The Birdcatcher, the Partridge, and the Cock",
    author: "Aesop",
    text: "A birdcatcher caught a partridge and a cock. The cock pleaded to be let go. The birdcatcher said, \"I pity you, but you are no better than the partridge.\" Do not expect mercy for the same crime as another.",
    length: "short",
    ageSuitability: "6+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-03-08T00:00:00Z",
    flagged: false,
  },
  {
    id: "f068",
    title: "The Ass, the Fox, and the Lion",
    author: "Aesop",
    text: "An ass and a fox conspired against the lion. The ass brayed to frighten the lion. The lion ate the ass. Treachery is punished.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-09T00:00:00Z",
    flagged: false,
  },
  {
    id: "f069",
    title: "The Lion, the Ass, and the Fox",
    author: "Aesop",
    text: "The lion, ass, and fox went hunting together. The ass fetched game from far away. The fox stole it. The lion said, \"You have labored; let us eat.\" Work hard, rest well.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "friendship"],
    language: "en",
    createdAt: "2025-03-10T00:00:00Z",
    flagged: false,
  },
  {
    id: "f070",
    title: "The Ass in the Lion's Skin",
    author: "Aesop",
    text: "An ass put on a lion's skin and frightened everyone. When he brayed, his voice gave him away. Fine clothes may disguise, but silly words will reveal a fool.",
    length: "short",
    ageSuitability: "4+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-11T00:00:00Z",
    flagged: false,
  },
  {
    id: "f071",
    title: "The Cock and the Jewel",
    author: "Aesop",
    text: "A cock found a jewel and said, \"I would rather have a barleycorn than all the jewels in the world.\" Each to their own values.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-12T00:00:00Z",
    flagged: false,
  },
  {
    id: "f072",
    title: "The Swallow and the Crow",
    author: "Aesop",
    text: "A swallow and a crow argued about who was more beautiful. The crow said, \"Your feathers are fair in summer, but mine keep me warm in winter.\" Function is more important than beauty.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "nature"],
    language: "en",
    createdAt: "2025-03-13T00:00:00Z",
    flagged: false,
  },
  {
    id: "f073",
    title: "The Bat, the Birds, and the Beasts",
    author: "Aesop",
    text: "A bat joined the birds, then the beasts. Both rejected him. He stayed alone. Choose a side and stick to it.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-14T00:00:00Z",
    flagged: false,
  },
  {
    id: "f074",
    title: "The Bee and the Zeus",
    author: "Aesop",
    text: "A bee brought honey to Zeus. Zeus was pleased and said, \"Ask anything.\" The bee asked for a sting to kill anyone who tried to take the honey. Zeus was sorry but had to grant it. Be careful what you wish for.",
    length: "short",
    ageSuitability: "6+",
    tags: ["magic", "wisdom"],
    language: "en",
    createdAt: "2025-03-15T00:00:00Z",
    flagged: false,
  },
  {
    id: "f075",
    title: "The Belly and the Members",
    author: "Aesop",
    text: "The members of the body went on strike against the belly. They refused to work. Soon they all weakened. The belly showed that it digested food for all. Cooperation is essential.",
    length: "short",
    ageSuitability: "5+",
    tags: ["friendship", "wisdom"],
    language: "en",
    createdAt: "2025-03-16T00:00:00Z",
    flagged: false,
  },
  {
    id: "f076",
    title: "The Oak and the Reed",
    author: "Aesop",
    text: "An oak tree boasted of its strength. A reed bent in the wind. A great storm came and the oak was uprooted, but the reed bent and survived. Flexibility is strength.",
    length: "short",
    ageSuitability: "5+",
    tags: ["nature", "wisdom"],
    language: "en",
    createdAt: "2025-03-17T00:00:00Z",
    flagged: false,
  },
  {
    id: "f077",
    title: "The Oak and the Travelers",
    author: "Aesop",
    text: "Travelers rested under a great oak. The tree creaked and groaned. They said, \"What a worthless tree!\" The tree replied, \"You who rest under me dare call me worthless?\" Be grateful for what helps you.",
    length: "short",
    ageSuitability: "5+",
    tags: ["nature", "kindness"],
    language: "en",
    createdAt: "2025-03-18T00:00:00Z",
    flagged: false,
  },
  {
    id: "f078",
    title: "The Crow and the Fox",
    author: "Aesop",
    text: "A crow found a piece of cheese and perched in a tree. A fox praised her voice and begged her to sing. The crow opened her beak, and the cheese fell. The fox snatched it and ran. Flattery takes what it wants.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-19T00:00:00Z",
    flagged: false,
  },
  {
    id: "f079",
    title: "The Eagle and the Jackdaw",
    author: "Aesop",
    text: "An eagle swooped down and caught a lamb. A jackdaw tried to do the same but got tangled in the shearing. The shepherd caught him. Do not try to do what is beyond your power.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-20T00:00:00Z",
    flagged: false,
  },
  {
    id: "f080",
    title: "The Farmer and the Stork (Second)",
    author: "Aesop",
    text: "A farmer found a stork among the cranes. The stork begged mercy. The farmer said, \"You flew with the cranes; you share their fate.\" You are judged by those you choose to be with.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-03-21T00:00:00Z",
    flagged: false,
  },
  {
    id: "f081",
    title: "The Two Pots",
    author: "Aesop",
    text: "Two pots floated down a river. One was clay, the other brass. The brass pot asked the clay pot to stay close. The clay pot said, \"If you come near, I will be broken. Better keep our distance.\" Those who are weaker must avoid the strong.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-22T00:00:00Z",
    flagged: false,
  },
  {
    id: "f082",
    title: "The Wolf and the Crane",
    author: "Aesop",
    text: "A wolf had a bone stuck in his throat. He begged a crane to pull it out. The crane did so and asked for a reward. The wolf said, \"You put your head in a wolf's mouth and took it out again. What greater reward could there be?\" Be grateful for your life.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-23T00:00:00Z",
    flagged: false,
  },
  {
    id: "f083",
    title: "The Dog and the Shadow",
    author: "Aesop",
    text: "A dog with a bone crossed a bridge and saw his shadow. He thought another dog had a bigger bone. He snapped and lost his own. Do not be greedy.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-24T00:00:00Z",
    flagged: false,
  },
  {
    id: "f084",
    title: "The Man and the Satyr",
    author: "Aesop",
    text: "A man and a satyr became friends. The man blew on his hands to warm them, then on his soup to cool it. The satyr left, saying, \"I cannot trust someone who blows hot and cold with the same breath.\" Be consistent.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-25T00:00:00Z",
    flagged: false,
  },
  {
    id: "f085",
    title: "The Vain Jackdaw",
    author: "Aesop",
    text: "A jackdaw found peacock feathers and wore them among the peacocks. They pecked him away. He tried to return to his own kind, but they rejected him too. He had become a stranger to both. Do not try to be what you are not.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-26T00:00:00Z",
    flagged: false,
  },
  {
    id: "f086",
    title: "The Fox Without a Tail",
    author: "Aesop",
    text: "A fox lost his tail. He tried to persuade other foxes to lose theirs. They refused. Better to be honest about your own misfortune.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-27T00:00:00Z",
    flagged: false,
  },
  {
    id: "f087",
    title: "The Birds, the Beasts, and the Bat",
    author: "Aesop",
    text: "The birds and beasts went to war. The bat joined the birds, then the beasts. When the birds won, the bat was banished. He flies only at night. Choose your side wisely.",
    length: "short",
    ageSuitability: "5+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-03-28T00:00:00Z",
    flagged: false,
  },
  {
    id: "f088",
    title: "The Frog and the Ox",
    author: "Aesop",
    text: "A frog told her son about the great ox. The frog puffed herself up to match the ox. She kept puffing until she burst. Do not try to be more than you are.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-29T00:00:00Z",
    flagged: false,
  },
  {
    id: "f089",
    title: "The Miser",
    author: "Aesop",
    text: "A miser dug up his gold every day to count it. A servant stole it. The miser wept. A neighbor said, \"Buy a stone and imagine it is your gold. It will serve the same purpose.\" Possession without use is pointless.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-30T00:00:00Z",
    flagged: false,
  },
  {
    id: "f090",
    title: "The Man and the Golden Egg",
    author: "Aesop",
    text: "A man had a goose that laid golden eggs. He killed it to find more gold inside. He found nothing special. Greed overreaches itself.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-03-31T00:00:00Z",
    flagged: false,
  },
  {
    id: "f091",
    title: "The Cobbler Turned Doctor",
    author: "Aesop",
    text: "A cobbler could not make enough to live. He traveled to a city and pretended to be a doctor. He was asked what he cured. \"The dead,\" he said. \"I bring them back to life.\" A patient died. The cobbler was asked to bring him back. He said, \"Only if it rains in eight days.\" If the patient lived, he would be praised. If he died, no one would blame him. Deception eventually fails.",
    length: "medium",
    ageSuitability: "6+",
    tags: ["honesty", "wisdom"],
    language: "en",
    createdAt: "2025-04-01T00:00:00Z",
    flagged: false,
  },
  {
    id: "f092",
    title: "The Fox and the Lion",
    author: "Aesop",
    text: "A fox saw a lion for the first time and was terrified. He saw him again and was less afraid. The third time he walked up and greeted him. Familiarity breeds contempt.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-04-02T00:00:00Z",
    flagged: false,
  },
  {
    id: "f093",
    title: "The Lion and the Boar",
    author: "Aesop",
    text: "A lion and a boar fought over water. Both were wounded. They saw vultures waiting. They stopped fighting. It is better to make peace than to be destroyed together.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "bravery"],
    language: "en",
    createdAt: "2025-04-03T00:00:00Z",
    flagged: false,
  },
  {
    id: "f094",
    title: "The Fox and the Grapes (Second)",
    author: "Aesop",
    text: "A fox tried to reach high grapes. He could not. He said, \"They are probably sour.\" It is easy to despise what you cannot attain.",
    length: "short",
    ageSuitability: "4+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-04-04T00:00:00Z",
    flagged: false,
  },
  {
    id: "f095",
    title: "The Farmer and the Eagle",
    author: "Aesop",
    text: "A farmer caught an eagle and cut off his wings. The eagle flew away. The farmer said, \"You cannot fly without wings.\" The eagle replied, \"You cannot fly without them either.\" Do not harm those who could help you.",
    length: "short",
    ageSuitability: "5+",
    tags: ["nature", "wisdom"],
    language: "en",
    createdAt: "2025-04-05T00:00:00Z",
    flagged: false,
  },
  {
    id: "f096",
    title: "The Lion and the Hare",
    author: "Aesop",
    text: "A lion chased a hare but lost it. He blamed himself for chasing a trifle when greater game was near. Do not let small gains distract you from larger opportunities.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-04-06T00:00:00Z",
    flagged: false,
  },
  {
    id: "f097",
    title: "The Bear and the Travelers",
    author: "Aesop",
    text: "Two travelers saw a bear. One climbed a tree. The other lay still. The bear sniffed him and left. The first traveler asked what the bear said. \"He said never trust a friend who deserts you in trouble.\" Judge friends by their actions.",
    length: "short",
    ageSuitability: "5+",
    tags: ["friendship", "wisdom"],
    language: "en",
    createdAt: "2025-04-07T00:00:00Z",
    flagged: false,
  },
  {
    id: "f098",
    title: "The Traveler and His Dog",
    author: "Aesop",
    text: "A traveler was about to start his journey. His dog stood at the door yawning. He said, \"Why do you yawn? If you were ready, we would go.\" Many are ready to talk but slow to act. Do not judge by appearances.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom"],
    language: "en",
    createdAt: "2025-04-08T00:00:00Z",
    flagged: false,
  },
  {
    id: "f099",
    title: "The Lion, the Fox, and the Stag",
    author: "Aesop",
    text: "A lion lay ill. The fox told the stag to visit the lion for a cure. The stag came and was eaten. The fox took the brain as payment. Do not trust those who betray others.",
    length: "short",
    ageSuitability: "6+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-04-09T00:00:00Z",
    flagged: false,
  },
  {
    id: "f100",
    title: "The Fox and the Mask",
    author: "Aesop",
    text: "A fox entered a mask-maker's shop and found a fine mask. He said, \"What a beautiful head — what a pity it has no brains.\" Appearance without substance is worthless.",
    length: "short",
    ageSuitability: "5+",
    tags: ["wisdom", "honesty"],
    language: "en",
    createdAt: "2025-04-10T00:00:00Z",
    flagged: false,
  },
];
